name: flutter_map_supercluster
description: Very fast Marker clustering for flutter_map. Supports efficient adding/removing of Markers.
version: 1.0.0

homepage: https://github.com/rorystephenson/flutter_map_supercluster

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_map_marker_popup: ^4.0.0
  latlong2: ^0.8.1
  provider: ^6.0.3
  supercluster: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
