name: flutter_map_supercluster
description: A very fast clustering layer for FlutterMap which uses the supercluster algorithm.
version: 0.0.1

homepage: https://github.com/rorystephenson/flutter_map_supercluster

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_map_marker_popup: ^4.0.0
  latlong2: ^0.8.1
  provider: ^6.0.3
  supercluster:
    path: ../supercluster

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
